// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SATSApp.Data;

#nullable disable

namespace SATSApp.Data.Migrations
{
    [DbContext(typeof(SATSAppDbContext))]
    [Migration("20240824095959_initialData")]
    partial class initialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SATSApp.Data.Entities.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CourseId"));

                    b.Property<string>("CourseDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("course_description");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("course_name");

                    b.Property<DateTime>("CreaDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("crea_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.HasKey("CourseId");

                    b.ToTable("Courses", "satsapp");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            CourseDescription = "Description for Course1",
                            CourseName = "Ozz Akademi1",
                            CreaDate = new DateTime(2024, 8, 24, 9, 59, 58, 913, DateTimeKind.Utc).AddTicks(2727),
                            IsDeleted = false
                        },
                        new
                        {
                            CourseId = 2,
                            CourseDescription = "Description for Course2",
                            CourseName = "Ozz Akademi2",
                            CreaDate = new DateTime(2024, 8, 24, 9, 59, 58, 913, DateTimeKind.Utc).AddTicks(2733),
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("SATSApp.Data.Entities.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StudentId"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birth_date");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreaDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("crea_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.HasKey("StudentId");

                    b.ToTable("Students", "satsapp");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            BirthDate = new DateTime(2023, 8, 25, 9, 59, 58, 913, DateTimeKind.Utc).AddTicks(2367),
                            City = "Bartın",
                            CreaDate = new DateTime(2024, 8, 24, 9, 59, 58, 913, DateTimeKind.Utc).AddTicks(2384),
                            Email = "NazlıÇetin@example.com",
                            FirstName = "Nazlı",
                            IsDeleted = false,
                            LastName = "Çetin"
                        },
                        new
                        {
                            StudentId = 2,
                            BirthDate = new DateTime(2022, 8, 25, 9, 59, 58, 913, DateTimeKind.Utc).AddTicks(2393),
                            City = "Bayburt",
                            CreaDate = new DateTime(2024, 8, 24, 9, 59, 58, 913, DateTimeKind.Utc).AddTicks(2396),
                            Email = "BüşraArslan@example.com",
                            FirstName = "Büşra",
                            IsDeleted = false,
                            LastName = "Arslan"
                        },
                        new
                        {
                            StudentId = 3,
                            BirthDate = new DateTime(2021, 8, 25, 9, 59, 58, 913, DateTimeKind.Utc).AddTicks(2399),
                            City = "Sivas",
                            CreaDate = new DateTime(2024, 8, 24, 9, 59, 58, 913, DateTimeKind.Utc).AddTicks(2400),
                            Email = "PinarÇakmak@example.com",
                            FirstName = "Pinar",
                            IsDeleted = false,
                            LastName = "Çakmak"
                        },
                        new
                        {
                            StudentId = 4,
                            BirthDate = new DateTime(2020, 8, 25, 9, 59, 58, 913, DateTimeKind.Utc).AddTicks(2403),
                            City = "Kırşehir",
                            CreaDate = new DateTime(2024, 8, 24, 9, 59, 58, 913, DateTimeKind.Utc).AddTicks(2406),
                            Email = "CanYavuz@example.com",
                            FirstName = "Can",
                            IsDeleted = false,
                            LastName = "Yavuz"
                        },
                        new
                        {
                            StudentId = 5,
                            BirthDate = new DateTime(2019, 8, 26, 9, 59, 58, 913, DateTimeKind.Utc).AddTicks(2486),
                            City = "Adana",
                            CreaDate = new DateTime(2024, 8, 24, 9, 59, 58, 913, DateTimeKind.Utc).AddTicks(2487),
                            Email = "BurakKaraoğlu@example.com",
                            FirstName = "Burak",
                            IsDeleted = false,
                            LastName = "Karaoğlu"
                        },
                        new
                        {
                            StudentId = 6,
                            BirthDate = new DateTime(2018, 8, 26, 9, 59, 58, 913, DateTimeKind.Utc).AddTicks(2496),
                            City = "Kars",
                            CreaDate = new DateTime(2024, 8, 24, 9, 59, 58, 913, DateTimeKind.Utc).AddTicks(2499),
                            Email = "EbruKara@example.com",
                            FirstName = "Ebru",
                            IsDeleted = false,
                            LastName = "Kara"
                        },
                        new
                        {
                            StudentId = 7,
                            BirthDate = new DateTime(2017, 8, 26, 9, 59, 58, 913, DateTimeKind.Utc).AddTicks(2503),
                            City = "Bursa",
                            CreaDate = new DateTime(2024, 8, 24, 9, 59, 58, 913, DateTimeKind.Utc).AddTicks(2505),
                            Email = "EbruGül@example.com",
                            FirstName = "Ebru",
                            IsDeleted = false,
                            LastName = "Gül"
                        },
                        new
                        {
                            StudentId = 8,
                            BirthDate = new DateTime(2016, 8, 26, 9, 59, 58, 913, DateTimeKind.Utc).AddTicks(2506),
                            City = "Erzincan",
                            CreaDate = new DateTime(2024, 8, 24, 9, 59, 58, 913, DateTimeKind.Utc).AddTicks(2509),
                            Email = "ElifKara@example.com",
                            FirstName = "Elif",
                            IsDeleted = false,
                            LastName = "Kara"
                        },
                        new
                        {
                            StudentId = 9,
                            BirthDate = new DateTime(2015, 8, 27, 9, 59, 58, 913, DateTimeKind.Utc).AddTicks(2511),
                            City = "Ardahan",
                            CreaDate = new DateTime(2024, 8, 24, 9, 59, 58, 913, DateTimeKind.Utc).AddTicks(2514),
                            Email = "NazlıKaya@example.com",
                            FirstName = "Nazlı",
                            IsDeleted = false,
                            LastName = "Kaya"
                        },
                        new
                        {
                            StudentId = 10,
                            BirthDate = new DateTime(2014, 8, 27, 9, 59, 58, 913, DateTimeKind.Utc).AddTicks(2520),
                            City = "Ağrı",
                            CreaDate = new DateTime(2024, 8, 24, 9, 59, 58, 913, DateTimeKind.Utc).AddTicks(2521),
                            Email = "MeryemÇakır@example.com",
                            FirstName = "Meryem",
                            IsDeleted = false,
                            LastName = "Çakır"
                        },
                        new
                        {
                            StudentId = 11,
                            BirthDate = new DateTime(2013, 8, 27, 9, 59, 58, 913, DateTimeKind.Utc).AddTicks(2522),
                            City = "Adana",
                            CreaDate = new DateTime(2024, 8, 24, 9, 59, 58, 913, DateTimeKind.Utc).AddTicks(2523),
                            Email = "SibelErdoğan@example.com",
                            FirstName = "Sibel",
                            IsDeleted = false,
                            LastName = "Erdoğan"
                        },
                        new
                        {
                            StudentId = 12,
                            BirthDate = new DateTime(2012, 8, 27, 9, 59, 58, 913, DateTimeKind.Utc).AddTicks(2524),
                            City = "Kastamonu",
                            CreaDate = new DateTime(2024, 8, 24, 9, 59, 58, 913, DateTimeKind.Utc).AddTicks(2525),
                            Email = "İsmailKurt@example.com",
                            FirstName = "İsmail",
                            IsDeleted = false,
                            LastName = "Kurt"
                        },
                        new
                        {
                            StudentId = 13,
                            BirthDate = new DateTime(2011, 8, 28, 9, 59, 58, 913, DateTimeKind.Utc).AddTicks(2527),
                            City = "Yalova",
                            CreaDate = new DateTime(2024, 8, 24, 9, 59, 58, 913, DateTimeKind.Utc).AddTicks(2528),
                            Email = "EbruÖzkan@example.com",
                            FirstName = "Ebru",
                            IsDeleted = false,
                            LastName = "Özkan"
                        },
                        new
                        {
                            StudentId = 14,
                            BirthDate = new DateTime(2010, 8, 28, 9, 59, 58, 913, DateTimeKind.Utc).AddTicks(2529),
                            City = "Aydın",
                            CreaDate = new DateTime(2024, 8, 24, 9, 59, 58, 913, DateTimeKind.Utc).AddTicks(2531),
                            Email = "TolgaKaraoğlu@example.com",
                            FirstName = "Tolga",
                            IsDeleted = false,
                            LastName = "Karaoğlu"
                        },
                        new
                        {
                            StudentId = 15,
                            BirthDate = new DateTime(2009, 8, 28, 9, 59, 58, 913, DateTimeKind.Utc).AddTicks(2532),
                            City = "Diyarbakır",
                            CreaDate = new DateTime(2024, 8, 24, 9, 59, 58, 913, DateTimeKind.Utc).AddTicks(2533),
                            Email = "CanerKaya@example.com",
                            FirstName = "Caner",
                            IsDeleted = false,
                            LastName = "Kaya"
                        },
                        new
                        {
                            StudentId = 16,
                            BirthDate = new DateTime(2008, 8, 28, 9, 59, 58, 913, DateTimeKind.Utc).AddTicks(2535),
                            City = "Konya",
                            CreaDate = new DateTime(2024, 8, 24, 9, 59, 58, 913, DateTimeKind.Utc).AddTicks(2536),
                            Email = "MustafaAksu@example.com",
                            FirstName = "Mustafa",
                            IsDeleted = false,
                            LastName = "Aksu"
                        },
                        new
                        {
                            StudentId = 17,
                            BirthDate = new DateTime(2007, 8, 29, 9, 59, 58, 913, DateTimeKind.Utc).AddTicks(2538),
                            City = "Tekirdağ",
                            CreaDate = new DateTime(2024, 8, 24, 9, 59, 58, 913, DateTimeKind.Utc).AddTicks(2539),
                            Email = "PinarÇelik@example.com",
                            FirstName = "Pinar",
                            IsDeleted = false,
                            LastName = "Çelik"
                        },
                        new
                        {
                            StudentId = 18,
                            BirthDate = new DateTime(2006, 8, 29, 9, 59, 58, 913, DateTimeKind.Utc).AddTicks(2542),
                            City = "Mersin",
                            CreaDate = new DateTime(2024, 8, 24, 9, 59, 58, 913, DateTimeKind.Utc).AddTicks(2543),
                            Email = "MuhammedKaraoğlu@example.com",
                            FirstName = "Muhammed",
                            IsDeleted = false,
                            LastName = "Karaoğlu"
                        },
                        new
                        {
                            StudentId = 19,
                            BirthDate = new DateTime(2005, 8, 29, 9, 59, 58, 913, DateTimeKind.Utc).AddTicks(2545),
                            City = "Kırklareli",
                            CreaDate = new DateTime(2024, 8, 24, 9, 59, 58, 913, DateTimeKind.Utc).AddTicks(2546),
                            Email = "CengizBozkurt@example.com",
                            FirstName = "Cengiz",
                            IsDeleted = false,
                            LastName = "Bozkurt"
                        },
                        new
                        {
                            StudentId = 20,
                            BirthDate = new DateTime(2004, 8, 29, 9, 59, 58, 913, DateTimeKind.Utc).AddTicks(2547),
                            City = "Kırklareli",
                            CreaDate = new DateTime(2024, 8, 24, 9, 59, 58, 913, DateTimeKind.Utc).AddTicks(2548),
                            Email = "GamzeUysal@example.com",
                            FirstName = "Gamze",
                            IsDeleted = false,
                            LastName = "Uysal"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
